### ISSUE TITLE
Draw by Mutual Homeworld Loss, Textbox Says: You'll Lose

### ISSUE THREAD

**Issue by SimonN** [jpeterbaker/bga_homeworlds#17]
Game: [me-Amnykon, 2022-07-22](https://boardgamearena.com/table?table=399217065).

In my last turn, I destroy his last homeworld star, but leave my own homeworld unoccupied. This will end the game in a draw by mutual homeworld loss. This draw is deliberate, I don't see anything better.

When I confirm the turn,  I get a textbox: "You have no ships at your homeworld and you will lose. Are you sure that this is what you want to do?" The text is wrong: I won't lose. I was confused enough to double-check that my move really destroyed his star. In hindsight, I understand the box: Losing is indeed the normal consequence of having no ships, and I understand that the box is a failsafe against nonsensical input first, and a rules reminder for newer players second.

Expected instead: A box that that tells me that this move will draw (not lose), or no box. I believe that having a box here is reasonable; maybe you have spare ships to fly back home.

**Comment by jpeterbaker** [comment]
It's supposed to detect upcoming draws and give you a corresponding warning. I'll try recreating your scenario and see what I missed.

**Comment by jpeterbaker** [comment]
This bug should have showed up in the most basic testing of the draw warning system, so I must have just flubbed it. Anyway, it's fixed.

**Comment by SimonN** [comment]
Thanks! I'll report here when I've drawn another game. Draws are rare.

**Comment by jpeterbaker** [comment]
I had actually intended to close the issue. I'm quite certain it's taken care of. If there's still a problem, it's going to be for a different reason and deserves a different issue.
