### ISSUE TITLE
php code allow capture of a star

### ISSUE THREAD

**Issue by ze42** [jpeterbaker/bga_homeworlds#2]
The code only checks if you are trying to [capture your own ship](https://github.com/jpeterbaker/bga_homeworlds/blob/master/homeworlds.game.php#L745), or [something that is not in the same system](https://github.com/jpeterbaker/bga_homeworlds/blob/master/homeworlds.game.php#L749), but nothing against capturing a star...

So, the JS would not let you do it, but a hack by calling the PHP directly could still let you capture a start.

Reloading would fail if you have ships in a system without any star (the interface would not know how to handle such), but you could properly:
* capture one of your own star (ie: an other size 3 ship on first round) and completly change the connexion between worlds
* move with a "small" harmless ship into the enemy base, and capture a small star, and only have to catastrophe the other

Beside that... breaking the game in a turn base game (where your opponent is probably not looking... and will have to reload the game...) could result in you forcing your opponent to timeout, and you kicking him out for time. - though he'd probably open a bug, and you could try to do something about ELO points.

**Comment by jpeterbaker** [comment]
I don't think a user could run whatever PHP they want, but I think there is a vulnerability here. I'll take care of this. Thanks!
