### ISSUE TITLE
During red sacrifice, omit need to click own ship

### ISSUE THREAD

**Issue by SimonN** [jpeterbaker/bga_homeworlds#8]
After I sacrifice a red ship, I would like to click directly on 1-3 opposing ships. See bottom of post for example.

The need to click own ships first makes sense because actions are only ever conducted by own ships. As consistent as it is from the game rules, it feels like I'm doing work for the computer that the computer should do for me. Unlike with yellow, green, and blue, there is nothing particular about the own ship that I choose other than its size. This difference feels enough like it warrants a UI difference.

From experience (not particular to BGA), whenever I sacrifice r2 or r3, it's usually to capture multiple invaders at the same star, and more rarely to capture invaders at several different stars. The UI annoyance is most glaring when I capture at the same star: Every other click must go on the same own big ship, which produces a zig-zagging mouse pattern between the group of opposing ships (left of star) and my ship (right of star). 

On the other hand, the click on the big own ship doesn't hurt, and it's consistent with all other sacrificing. Thus I recommend that the UI allow both styles: Click the own ship, then the target, or immediately click the target.

* * *

**Current BGA sacrifice:**
Click own r3 ship to select it for activation or sacrifice.
Click Sacrifice.
Click own biggest ship.
Click 1st opposing ship.
Click the same own ship again.
Click 2nd opposing ship.
Click the same own ship yet agian.
Click 3rd opposing ship.

**Expected in addition:**
Click own r3 ship to select it for activation or sacrifice.
Click Sacrifice.
Click 1st opposing ship.
Click 2nd opposing ship.
Click 3rd opposing ship.

**Comment by jpeterbaker** [comment]
This is now a feature that can be enabled from the options menu. Thanks for the suggestion!

**Comment by SimonN** [comment]
I activated one-click capture. I can capture enemy ships as the basic action, before clicking an own ship, very nice. Capturable enemy ships highlight on mouseover, and bigger enemy ships do not highlight. Nice!

Thanks for implementing this with all the extra details!

**Comment by SimonN** [comment]
Half a year later: One-click capture is so comfortable, it's wonderful. There is zero ambiguity when we click opposing ships. Great!
